# Datos del proyecto (vistos en tu SonarQube)
sonar.projectKey=mantenimiento_test
sonar.projectName=mantenimiento_test
sonar.host.url=http://localhost:9000

# Aquí pega el token que generaste en el paso anterior
sonar.token=squ_6111af136306326cc681c93bcd21032ba802d822

# Configuración de carpetas
sonar.sources=src,public
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.projectVersion=1.0.0

# Configuración del lenguaje
sonar.language=js
sonar.javascript.environments=node,browser
sonar.sourceEncoding=UTF-8